-- ==========================================
-- STUDY SYNC: PERSISTENT LABORATORY SCHEMA
-- ==========================================

-- 1. Create StudySync Messages Table (Persistent History)
-- Prefix: studysync_
CREATE TABLE IF NOT EXISTS public.studysync_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create StudySync File Metadata Table (Library Records)
CREATE TABLE IF NOT EXISTS public.studysync_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size BIGINT,
    uploader_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Realtime for StudySync Tables
-- This allows browser clients to receive instant updates for chat and files.
ALTER PUBLICATION supabase_realtime ADD TABLE public.studysync_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.studysync_files;

-- 4. Create the Storage Bucket for StudySync Files
-- This bucket stores the actual binary data for the Study Library.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('studysync_files', 'studysync_files', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Row Level Security (RLS) Configuration
-- For this school project, we allow public access to the laboratory data.
ALTER TABLE public.studysync_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studysync_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow All for Messages" ON public.studysync_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All for Files" ON public.studysync_files FOR ALL USING (true) WITH CHECK (true);

-- 6. Storage Bucket Security Policies
-- Allow anyone to upload and download from the studysync_files bucket.
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'studysync_files');
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'studysync_files');
